npxi_sesh = '2023-10-03_14-49-28';
npxi_exper = 'experiment8/recording1';
task_sesh = '03-Oct-2023 15_40_30';

task_data_p = fullfile( ...
  'C:\Users\setup2\source\setup2_ni\task\data', task_sesh );
npxi_data_p = fullfile( ...
  'C:\Users\setup2\Documents\Open Ephys\data\test', npxi_sesh ...
  , 'Record Node 101', npxi_exper, 'continuous\Neuropix-PXI-100.ProbeA-AP' ...
);

validate_npxi_video_sync( ...
    fullfile(task_data_p, 'video_1.mp4') ...
  , fullfile(task_data_p, 'video_2.mp4') ...
  , fullfile(task_data_p, 'ni.bin') ...
  , fullfile(npxi_data_p, 'continuous.dat') ...
);